git:
  depth: false
language: minimal
matrix:
  include:
  - before_cache:
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/liblorri.rlib"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/lorri*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/build/lorri-*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/lorri-*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/liblorri-*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/lorri-*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/.fingerprint/lorri-*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/build_script_build-*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/direnv-*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/direnv-*"
    - rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/direnv-*"
    cache:
      directories:
      - $HOME/.cargo
      - $TRAVIS_BUILD_DIR/target
    env:
    - CACHE_NAME=linux
    language: nix
    name: cargo build & linters
    nix: 2.3.1
    os: linux
    script:
    - set -e
    - nix-build -A allBuildInputs shell.nix > ./shell-inputs
    - nix-shell --quiet --arg isDevelopmentShell false --run ci_check
    - cat $(nix-build --quiet ./.travis.yml.nix --no-out-link) > .travis.yml
    - git diff -q ./.travis.yml
    - git diff -q ./Cargo.nix
    - git diff -q ./src/com_target_lorri.rs
